# Generated by Django 5.2.6 on 2025-10-19 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa_de_Ayuda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Mesa_de_Ayuda.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_progreso', 'En Progreso'), ('cerrada', 'Cerrada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[('low', 'Baja'), ('med', 'Media'), ('high', 'Alta')], max_length=50),
        ),
    ]
